# Generated by Django 4.0.10 on 2025-09-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
